import os
import pandas as pd
from fpdf import FPDF
from datetime import datetime
from langchain_groq import ChatGroq
from database import get_engine
from dotenv import load_dotenv

load_dotenv()


def generate_llm_summary(kpis: dict) -> str:
    """Ask Groq LLM to write an executive summary based on KPIs."""
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        api_key=os.getenv("GROQ_API_KEY"),
        temperature=0.3,
    )

    prompt = f"""
    You are a senior business analyst. Write a concise executive summary (4-5 sentences)
    based on these business KPIs. Be specific, professional, and include one recommendation.

    KPIs:
    - Total Revenue: ${kpis.get('total_revenue', 0):,.2f}
    - Total Profit: ${kpis.get('total_profit', 0):,.2f}
    - Profit Margin: {kpis.get('profit_margin', 0):.1f}%
    - Total Orders: {kpis.get('total_orders', 0):,}
    - Top Region: {kpis.get('top_region', 'N/A')}
    - Top Category: {kpis.get('top_category', 'N/A')}
    - Top Product: {kpis.get('top_product', 'N/A')}

    Write the summary now:
    """

    response = llm.invoke(prompt)
    return response.content


def run_report_agent(output_path: str = "./data/report.pdf") -> dict:
    """
    Generates a PDF business report with KPIs and AI-written summary.
    """
    engine = get_engine()

    try:
        df = pd.read_sql("SELECT * FROM sales", con=engine)
    except Exception as e:
        return {"error": f"Could not read sales table: {str(e)}"}

    # ── Calculate KPIs ─────────────────────────────────────────────────────
    sales_col = next((c for c in df.columns if c == "sales"), None)
    profit_col = next((c for c in df.columns if c == "profit"), None)

    kpis = {}

    if sales_col:
        kpis["total_revenue"] = float(df[sales_col].sum())
    if profit_col:
        kpis["total_profit"] = float(df[profit_col].sum())
        kpis["profit_margin"] = (
            (kpis["total_profit"] / kpis["total_revenue"] * 100)
            if kpis.get("total_revenue")
            else 0
        )

    kpis["total_orders"] = len(df)

    if "region" in df.columns and sales_col:
        kpis["top_region"] = df.groupby("region")[sales_col].sum().idxmax()

    if "category" in df.columns and sales_col:
        kpis["top_category"] = df.groupby("category")[sales_col].sum().idxmax()

    if "product_name" in df.columns and sales_col:
        kpis["top_product"] = df.groupby("product_name")[sales_col].sum().idxmax()

    # ── Get LLM summary ────────────────────────────────────────────────────
    try:
        ai_summary = generate_llm_summary(kpis)
    except Exception:
        ai_summary = "AI summary unavailable. Please check your Groq API key."

    # ── Build PDF ──────────────────────────────────────────────────────────
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 30, 60)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 15, "AI Business Intelligence Report", new_x="LMARGIN", new_y="NEXT", fill=True, align="C")

    # Date
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Executive Summary
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 10, "Executive Summary (AI-Generated)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    safe_summary = ai_summary.encode("latin-1", errors="replace").decode("latin-1")
    pdf.multi_cell(0, 7, safe_summary)
    pdf.ln(5)

    # KPI Table
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 60)
    pdf.cell(0, 10, "Key Performance Indicators", new_x="LMARGIN", new_y="NEXT")

    kpi_rows = [
        ("Total Revenue", f"${kpis.get('total_revenue', 0):,.2f}"),
        ("Total Profit", f"${kpis.get('total_profit', 0):,.2f}"),
        ("Profit Margin", f"{kpis.get('profit_margin', 0):.1f}%"),
        ("Total Orders", f"{kpis.get('total_orders', 0):,}"),
        ("Top Region", kpis.get("top_region", "N/A")),
        ("Top Category", kpis.get("top_category", "N/A")),
        ("Top Product", str(kpis.get("top_product", "N/A"))[:50]),
    ]

    pdf.set_font("Helvetica", "", 10)
    for i, (label, value) in enumerate(kpi_rows):
        fill = i % 2 == 0
        pdf.set_fill_color(240, 242, 255) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(90, 9, label, border=1, fill=fill)
        pdf.cell(100, 9, value, border=1, fill=fill, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)

    # Footer
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by AI Business Intelligence Analyst - Powered by Groq LLM", align="C")

    # Save
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    pdf.output(output_path)

    return {
        "status": "success",
        "report_path": output_path,
        "kpis": kpis,
        "ai_summary": ai_summary,
    }